### ISSUE TITLE
Support for Microsoft Graph

### ISSUE THREAD

**Issue by jonryf** [isac322/OneDrive-SDK-java#13]
Hey!
Might be a compilation error, but it does not seem to support Microsoft Graph:

The following error occurs upon client.getRootDir() call, using this scope;
`        String[] scope = {"Files.ReadWrite", "offline_access", "Files.ReadWrite.AppFolder"};`

`Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonGenerator.writeStartObject(Ljava/lang/Object;)V
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:295)
	at com.fasterxml.jackson.databind.ser.std.SerializableSerializer.serialize(SerializableSerializer.java:39)
	at com.fasterxml.jackson.databind.ser.std.SerializableSerializer.serialize(SerializableSerializer.java:20)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3716)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3656)
	at com.bhyoo.onedrive.container.items.DefaultFolderItem.addChildren(DefaultFolderItem.java:56)
	at com.bhyoo.onedrive.container.items.DefaultFolderItem.parseChildren(DefaultFolderItem.java:122)
	at com.bhyoo.onedrive.container.items.DefaultFolderItem$PointerInjector.convert(DefaultFolderItem.java:283)
	at com.bhyoo.onedrive.container.items.DefaultFolderItem$PointerInjector.convert(DefaultFolderItem.java:276)
	at com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer.convertValue(StdDelegatingDeserializer.java:246)
	at com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer.deserialize(StdDelegatingDeserializer.java:173)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1234)
	at com.bhyoo.onedrive.client.RequestTool.parseAndHandle(RequestTool.java:544)
	at com.bhyoo.onedrive.client.RequestTool.parseFolderItemAndHandle(RequestTool.java:520)
	at com.bhyoo.onedrive.client.Client.getRootDir(Client.java:168)`

**Comment by isac322** [comment]
Hello,
Thank you for the bug report.
Currently i'm working on the issue on [jackson-databind_to_stream](https://github.com/isac322/OneDrive-SDK-java/tree/jackson-databind_to_stream) branch. you can use Graph on the branch.
But because i'm Master degree student yet, the progress is slow.

**Comment by jonryf** [comment]
Hey!
Thanks for quick reply. I understand, thanks for updating me.

- minelazz

**Comment by jonryf** [comment]
Using running the following code:
` client.uploadFile(new PathPointer("/my-file.txt"), file.toPath());`

I get the following error. Is this related to the issue above? I am in the jackson-databind_to_stream branch.

`Mar 25, 2018 4:34:03 PM io.netty.util.concurrent.DefaultPromise notifyListener0
WARNING: An exception was thrown by com.bhyoo.onedrive.client.RequestTool$3.operationComplete()
com.bhyoo.onedrive.exceptions.ErrorResponseException: Expected 200 response code, but received 400. It means BadRequest (Unsupported segment type. ODataQuery: drive/root/upload.createSession).
	at com.bhyoo.onedrive.client.RequestTool.parseAndHandle(RequestTool.java:177)
	at com.bhyoo.onedrive.client.RequestTool.parseUploadSessionAndHandle(RequestTool.java:782)
	at com.bhyoo.onedrive.client.RequestTool$3.operationComplete(RequestTool.java:499)
	at com.bhyoo.onedrive.client.RequestTool$3.operationComplete(RequestTool.java:496)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:512)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:34)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:436)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by isac322** [comment]
It's my fault.
In fact, the first parameter of `Client.uploadFile` means __*parent*__ path to upload.
So in your case, the statement should be `client.uploadFile(new PathPointer("/"), file.toPath());` or more shortly `client.uploadFile(PathPointer.root, file.toPath());`.

Since I have committed the patch, please check again.
